### ISSUE TITLE
Featurerequest: configurable amount of entrees

### ISSUE THREAD

**Issue by Zevac-ZSF** [Lortseam/ugly-scoreboard-fix#1]
Hi, does your mod support extending the amount of entrees shown on the scoreboard? Vanilla shows max 15, but it would be nice to be able to show more.

Thanks in advance :-)

Z.

**Comment by Lortseam** [comment]
This is currently not supported, but should be easy to implement.

**Comment by Zevac-ZSF** [comment]
Nice :-)

**Comment by Lortseam** [comment]
Added in 2.8.0.
