### ISSUE TITLE
configure utility

### ISSUE THREAD

**Issue by liangmoe** [Lortseam/ugly-scoreboard-fix#12]
The settings been changed in game will not apply, need to restart the game to apply it
also -Hiding options
            ↳Key-binding to manually toggle sidebar visibility- is not working
im pretty sure there is no other hot key conflicting it

**Comment by Lortseam** [comment]
What version of this mod and Minecraft are you using?

**Comment by liangmoe** [comment]
sorry, im using uglyscoreboardfix-2.10.0 with minecraft 1.20.1

**Comment by Lortseam** [comment]
I cannot reproduce the issues you described. What other mods do you use? You can also disable all other mods and try again.

**Comment by liangmoe** [comment]
it is bc exordium, not your mod issue, it can be configured exordium's settings by toggle on "Force Scoreboard Updates". thanks for the reply!
