### ISSUE TITLE
Featurerequest: have multiple objectives show in a timed loop

### ISSUE THREAD

**Issue by Zevac-ZSF** [Lortseam/ugly-scoreboard-fix#2]
Hi again, I saw that you've already been working on my other request, thank you sooo much :-)

Because running into the issue of max lines of players on the scoreboard, I started thinking about the abilitity to show multiple objectives, like changing every couple of seconds, currently I use one primary objective for showing which mobswitches and farms are running, (that hit the 15 lines limit), but I would also love to have an objective showing which Autocrafters are running. it would be perfect if the scoreboard could switch between those two (or even more?) objectives every x seconds.

Cheers

Z.

**Comment by Lortseam** [comment]
I don't think this mod is the right place to implement that feature as it's quite server-specific and this mod should be focused on the client side.

I'm not sure if that's possible, but maybe you can switch between objectives using command blocks?

**Comment by Zevac-ZSF** [comment]
Are you sure? I mean my use of it is very specific, I realize that, but wouldn't the option to show multiple objectives be interesting for a lot of situations? like in mini-games showing both a gain-type objective and a loss-type of objective (like how many treasure items you found, but also how often you died during this run) or on an SMP server like Hermitcraft, when they do a game-day running multiple games? or where they have a long turn objective, and a secondary short term one?

Hang on, just re-read your comment, I get it now, you only change appearance of the scoreboard which is clientside only...

that is too bad... but I will for sure use your mod when you have the extra lines implemented :-)

I think I can make it work with some commandblocks, thanx for the hint!

**Comment by Lortseam** [comment]
> Are you sure? I mean my use of it is very specific, I realize that, but wouldn't the option to show multiple objectives be interesting for a lot of situations? like in mini-games showing both a gain-type objective and a loss-type of objective (like how many treasure items you found, but also how often you died during this run) or on an SMP server like Hermitcraft, when they do a game-day running multiple games? or where they have a long turn objective, and a secondary short term one?

Problem is the user would need to know the name of the objectives he would like to be displayed, and that's just not the case on most servers.

> Hang on, just re-read your comment, I get it now, you only change appearance of the scoreboard which is clientside only...
> 
> that is too bad... but I will for sure use your mod when you have the extra lines implemented :-)

Actually, I'm not sure if this would be possible to implement on the clientside only. What I wanted to say is that your feature request is probably better suited for a server plugin than this mod.

Edit: I just took a look at the code and it looks like it's in fact not possible to implement this feature with a clientside mod only.
