### ISSUE TITLE
No config button in Mod Menu

### ISSUE THREAD

**Issue by Clozent** [Lortseam/ugly-scoreboard-fix#7]
Having this mod and Mod Menu installed, and going to the mods menu, it will display this mod's icon as a grey question mark, and not show the config button.

**Comment by Felix14-v2** [comment]
Affects at least 1.16.5 and latest 1.19.4 versions. Both CompleteConfig and ClothConfig are installed.

**Comment by notrohit1702** [comment]
Same

**Comment by Lortseam** [comment]
This is caused by Mod Menu, please update Mod Menu to the latest version and try again.

**Comment by NotADinosaur** [comment]
I have latest modmenu (6.2.2) and this still happens

**Comment by Lortseam** [comment]
Fixed in version 2.10.0 (Minecraft 1.20.1 only). For Minecraft 1.19.4, please use Mod Menu version 6.1.0 or earlier.
