### ISSUE TITLE
Cannot log to servers with 

### ISSUE THREAD

**Issue by Ranzuu** [Lortseam/ugly-scoreboard-fix#9]
Hello there. I'm using:
**Ugly Scoreboard Fix 2.10.0 Fabric**
and
**CompleteConfig 2.5.0 Fabric**
for Minecraft version 1.20.2

Every time I join server (eg. Hypixel) I have normal loading screen, then short glimpse of the world and the game freeze. I'm sure this is problem of either 1st or 2nd listed above mod. Can access the config of the mod, but cannot property join the servers.
Any possible solutions to fix this?

**Comment by Lortseam** [comment]
Thanks for reporting, fixed in Ugly Scoreboard Fix 2.10.1.
